### ISSUE TITLE
missing ignore mask in sample dataset

### ISSUE THREAD

**Issue by cwlinghk** [openpifpaf/openpifpaf#438]
When I follow the guide here
https://openpifpaf.github.io/plugins_apollocar3d.html

to train the dataset:
https://ad-apolloscape.cdn.bcebos.com/3d_car_instance_sample.tar.gz

I found that the sample data does not have the directory "ignore_mask" and thus I stunned at the training command. 
May I know is it possible to train with the sample dataset?

And, is it possible if I have a custom keypoint dataset with a different topology? 
Thanks

**Comment by svenkreiss** [comment]
I am not sure, but I might have had the same issue with the sample data set. It's a bit annoying. Try the proper training data set.

You can definitely use custom keypoint datasets. In fact, Apollo is itself a customization of the COCO keypoint set for persons. Maybe take a look at the tutorial that walks through the customization for COCO-style datasets like Apollo that @bertoni9 wrote up: https://openpifpaf.github.io/plugins_custom.html

If you run into any issues, feel free to post back here.

**Comment by senanursahin** [comment]
Hello @svenkreiss, like you said I tried to use the proper training data set (3d-car-understanding-train.tar.gz) but when I click on that link it redirects to a login page and it's impossible to login via google or github. With google it raises an 400 error and with github it redirects to the same login page. 

I am working on implementing lane detection with openpifpaf project and I thought it is a good idea to use apollo's lane segmentation dataset since the project already has apollocar3d plugin and apollo_to_coco.py converter. But either in sample and train datasets of lane segmentation there is nothing related with ignore_mask. @bertoni9  @DuncanZauss could you please help me if I can use apollo's lane segmentation dataset without ignore_mask and still can use your apollo_to_coco.py converter, or any suggestion for how to proceed? 

Also can you please give information about how you define the constants (keypoints, skeleton numeric values etc.) in constants.py file, are you extracting it from annotation json file, shall I define 4 keypoints for example for my lane estimation plugin approach (and if so how to define the numeric values like skeleton, kps mapping etc.)?

Thanks in advance!
